# Generated by Django 5.1.7 on 2026-08-31 19:41

import chat_session.utils.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0013_chatbotcapacity'),
        ('lead_capture', '0002_consolidate_collectable_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('web_widget', 'Web widget'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('api', 'API')], default='web_widget', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('need_attention', 'Need Attention'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='active', max_length=24)),
                ('visitor_id', models.CharField(blank=True, db_index=True, default='', help_text='Anonymous fingerprint/cookie ID used to correlate sessions from the same unidentified visitor. Ignored once `lead` is set.', max_length=255)),
                ('external_thread_id', models.CharField(blank=True, default='', help_text='Channel-native conversation identifier — Messenger PSID, Instagram IGSID, WhatsApp phone number, or an API-side conversation key. Used to resume an existing session on inbound webhook events instead of creating a duplicate.', max_length=255)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ai_enabled', models.BooleanField(default=True, verbose_name='AI Enabled')),
                ('user_metadata', models.JSONField(blank=True, default=dict, help_text='Channel-specific session context stored as a JSON object.', validators=[chat_session.utils.validators.validate_json_object])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Channel-specific session context stored as a JSON object.', validators=[chat_session.utils.validators.validate_json_object])),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Denormalized pointer to the chatbot member currently responsible for this session. Kept in sync with the latest open ChatSessionTakeover row by the service layer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chat_sessions', to='chatbot.chatbotuser')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chatbot.chatbot')),
                ('lead', models.ForeignKey(blank=True, help_text='Set once the visitor is identified (e.g. via a lead-capture form or matched contact info). Null means the session is anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='lead_capture.lead')),
            ],
            options={
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('visitor', 'Visitor'), ('ai', 'AI'), ('agent', 'Agent'), ('system', 'System')], max_length=12)),
                ('content', models.TextField(blank=True, default='', help_text='May be blank for attachment-only messages (see attachments).')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], db_index=True, default='sent', max_length=12)),
                ('external_id', models.CharField(blank=True, default='', help_text='Optional channel message ID used for idempotent ingestion.', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Delivery, AI, citation, or channel data stored as a JSON object.', validators=[chat_session.utils.validators.validate_json_object])),
                ('sender', models.ForeignKey(blank=True, help_text='Set only when sender_type is agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='chatbot.chatbotuser')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_session.chatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatSessionTakeover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, choices=[('reassigned', 'Reassigned'), ('manual_release', 'Manual Release'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session_takeovers', to='chatbot.chatbotuser')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeovers', to='chat_session.chatsession')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_session_reopenings', to='chatbot.chatbotuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=12)),
                ('file_url', models.URLField(max_length=2048)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes.', null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='For audio/video attachments.', null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat_session.chatmessage')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['chat_message'], name='chat_attachment_message_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['chatbot', 'status', '-last_activity_at'], name='chat_session_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['assigned_to', 'status', '-last_activity_at'], name='chat_session_agent_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['chatbot', 'visitor_id'], name='chat_session_visitor_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['lead'], name='chat_session_lead_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('external_thread_id', ''), _negated=True), fields=('chatbot', 'channel', 'external_thread_id'), name='unique_external_thread_per_channel'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_session', 'created_at'], name='chat_message_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_session', 'status', 'created_at'], name='chat_message_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('sender_type', 'agent'), models.Q(('sender__isnull', True), ('sender_type__in', ['visitor', 'ai', 'system'])), _connector='OR'), name='chat_message_sender_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('chat_session', 'external_id'), name='unique_external_chat_message'),
        ),
        migrations.AddIndex(
            model_name='chatsessiontakeover',
            index=models.Index(fields=['chat_session', '-created_at'], name='chat_takeover_session_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsessiontakeover',
            index=models.Index(fields=['agent', '-created_at'], name='chat_takeover_agent_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatsessiontakeover',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('chat_session',), name='unique_active_takeover_per_session'),
        ),
        migrations.AddConstraint(
            model_name='chatsessiontakeover',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('release_reason', ''), ('released_at__isnull', True)), models.Q(('release_reason__gt', ''), ('released_at__isnull', False)), _connector='OR'), name='chat_takeover_release_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='chatsessiontakeover',
            constraint=models.CheckConstraint(condition=models.Q(('reopened_at__isnull', True), ('release_reason__in', ['resolved', 'closed']), _connector='OR'), name='chat_takeover_reopen_requires_resolution'),
        ),
    ]
