# Generated by Django 5.1.7 on 2026-09-05 08:32

import chat_session.utils.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_chat_session_lifecycle(apps, schema_editor):
    ChatSession = apps.get_model("chat_session", "ChatSession")
    ChatSessionTakeover = apps.get_model("chat_session", "ChatSessionTakeover")

    ChatSession.objects.filter(status="active").update(status="open")
    ChatSession.objects.filter(status="need_attention").update(
        status="open",
        requires_attention=True,
        attention_reason="other",
        attention_requested_at=models.F("last_activity_at"),
    )
    for session in ChatSession.objects.filter(status__in=("resolved", "closed")):
        terminal_at = session.ended_at or session.updated_at
        if session.status == "resolved":
            session.resolved_at = terminal_at
            session.save(update_fields=["resolved_at"])
        else:
            session.closed_at = terminal_at
            session.save(update_fields=["closed_at"])

    ChatSessionTakeover.objects.filter(release_reason="reassigned").update(
        release_reason="transferred"
    )
    ChatSessionTakeover.objects.filter(release_reason="manual_release").update(
        release_reason="released"
    )


def reverse_chat_session_lifecycle(apps, schema_editor):
    ChatSession = apps.get_model("chat_session", "ChatSession")
    ChatSessionTakeover = apps.get_model("chat_session", "ChatSessionTakeover")

    for session in ChatSession.objects.all():
        if session.status == "resolved":
            session.ended_at = session.resolved_at
        elif session.status == "closed":
            session.ended_at = session.closed_at
        if session.status == "open":
            session.status = "need_attention" if session.requires_attention else "active"
        session.save(update_fields=["status", "ended_at"])

    ChatSessionTakeover.objects.filter(release_reason="transferred").update(
        release_reason="reassigned"
    )
    ChatSessionTakeover.objects.filter(release_reason="released").update(
        release_reason="manual_release"
    )


class Migration(migrations.Migration):

    # PostgreSQL cannot alter ChatSession later in this migration while the
    # lifecycle data update has pending FK trigger events in the same
    # transaction. Commit between operations, while keeping the data rewrite
    # itself atomic.
    atomic = False

    dependencies = [
        ('chat_session', '0001_initial'),
        ('chatbot', '0013_chatbotcapacity'),
        ('lead_capture', '0002_consolidate_collectable_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSessionTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='chatmessageattachment',
            name='height',
        ),
        migrations.RemoveField(
            model_name='chatmessageattachment',
            name='width',
        ),
        migrations.RemoveField(
            model_name='chatsessiontakeover',
            name='reopened_by',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='attention_reason',
            field=models.CharField(blank=True, choices=[('human_requested', 'Human Requested'), ('ai_uncertain', 'AI Unable to Answer'), ('tool_failed', 'Tool Failed'), ('escalated', 'Escalated'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='attention_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_visitor_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='requires_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsessiontakeover',
            name='released_to',
            field=models.ForeignKey(blank=True, help_text='The agent this session was handed to, when release_reason=TRANSFERRED.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_chat_takeovers', to='chatbot.chatbotuser'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Human agent currently responsible for this session, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chat_sessions', to='chatbot.chatbotuser'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='channel',
            field=models.CharField(choices=[('web_widget', 'Web Widget'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('api', 'API')], default='web_widget', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Internal/channel-specific session context stored as a JSON object.', validators=[chat_session.utils.validators.validate_json_object]),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Visitor-side context captured before/without a Lead — IP, detected location, name, email, browser, etc.', validators=[chat_session.utils.validators.validate_json_object]),
        ),
        migrations.AlterField(
            model_name='chatsessiontakeover',
            name='release_reason',
            field=models.CharField(blank=True, choices=[('transferred', 'Transferred'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('released', 'Released')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsessiontakeover',
            name='reopened_at',
            field=models.DateTimeField(blank=True, help_text='Set if a session resolved/closed under this takeover was reopened.', null=True),
        ),
        migrations.RunPython(
            migrate_chat_session_lifecycle,
            reverse_chat_session_lifecycle,
            atomic=True,
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='ended_at',
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['chatbot', 'requires_attention', '-last_activity_at'], name='chat_session_attention_idx'),
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_session_lead_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessageattachment',
            name='chat_attachment_message_idx',
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attention_reason', ''), ('attention_requested_at__isnull', True), ('requires_attention', False)), models.Q(('attention_reason__gt', ''), ('attention_requested_at__isnull', False), ('requires_attention', True)), _connector='OR'), name='chat_session_attention_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('resolved_at__isnull', True), ('status', 'open')), models.Q(('closed_at__isnull', True), ('resolved_at__isnull', False), ('status', 'resolved')), models.Q(('closed_at__isnull', False), ('resolved_at__isnull', True), ('status', 'closed')), _connector='OR'), name='chat_session_lifecycle_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='chatsessiontakeover',
            constraint=models.CheckConstraint(condition=models.Q(('released_to__isnull', True), ('release_reason', 'transferred'), _connector='OR'), name='chat_takeover_released_to_requires_transfer'),
        ),
        migrations.AddField(
            model_name='chatsessiontransfer',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='chat_session.chatsession'),
        ),
        migrations.AddField(
            model_name='chatsessiontransfer',
            name='from_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_chat_transfers', to='chatbot.chatbotuser'),
        ),
        migrations.AddField(
            model_name='chatsessiontransfer',
            name='to_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_chat_transfers', to='chatbot.chatbotuser'),
        ),
        migrations.AddIndex(
            model_name='chatsessiontransfer',
            index=models.Index(fields=['chat_session', '-created_at'], name='chat_transfer_session_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsessiontransfer',
            index=models.Index(fields=['to_agent', 'status', '-created_at'], name='chat_transfer_to_agent_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatsessiontransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('chat_session',), name='unique_pending_transfer_per_session'),
        ),
        migrations.AddConstraint(
            model_name='chatsessiontransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_agent', models.F('to_agent')), _negated=True), name='chat_transfer_distinct_agents'),
        ),
        migrations.AddConstraint(
            model_name='chatsessiontransfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'pending')), models.Q(models.Q(('status', 'pending'), _negated=True), ('completed_at__isnull', False)), _connector='OR'), name='chat_transfer_completed_at_consistent'),
        ),
    ]
