# Generated by Django 5.1.7 on 2026-08-25 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0008_chatbot_escalation_rule_chatbot_never_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(choices=[('file', 'File'), ('website', 'Website'), ('text', 'Text')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('file_key', models.CharField(blank=True, max_length=1024)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True)),
                ('extracted_content', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='chatbot.chatbot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTrainingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('indexing', 'Indexing'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('processed_chunks', models.PositiveIntegerField(default=0)),
                ('force_retrain', models.BooleanField(default=False)),
                ('content_changed', models.BooleanField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='knowledge.knowledgebase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['chatbot', 'source_type'], name='kb_chatbot_source_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['chatbot', 'status'], name='kb_chatbot_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['chatbot', 'is_enabled'], name='kb_chatbot_enabled_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'website'), _negated=True), models.Q(('url__isnull', False), models.Q(('url', ''), _negated=True)), _connector='OR'), name='kb_website_requires_url'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'file'), _negated=True), models.Q(('file_key', ''), _negated=True), _connector='OR'), name='kb_file_requires_key'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'text'), _negated=True), models.Q(('text_content', ''), _negated=True), _connector='OR'), name='kb_text_requires_content'),
        ),
        migrations.AddIndex(
            model_name='knowledgetraininglog',
            index=models.Index(fields=['knowledge_base', 'stage'], name='kb_log_source_stage_idx'),
        ),
    ]
