# Generated by Django 5.1.7 on 2026-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='knowledgetraininglog',
            constraint=models.UniqueConstraint(condition=models.Q(('stage__in', ['queued', 'extracting', 'chunking', 'embedding', 'indexing'])), fields=('knowledge_base',), name='unique_active_training_per_source'),
        ),
    ]
