# Generated by Django 5.1.7 on 2026-09-13 15:01

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0005_add_lead_capture_to_supported_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage points or a fixed monetary amount.', max_digits=12)),
                ('currency', models.CharField(blank=True, help_text='Required for fixed discounts and blank for percentage discounts.', max_length=3)),
                ('duration', models.CharField(choices=[('once', 'Once'), ('repeating', 'Repeating'), ('forever', 'Forever')], default='once', max_length=12)),
                ('duration_in_billing_cycles', models.PositiveIntegerField(blank=True, help_text='Required only for repeating discounts.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('max_redemptions_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_purchase_currency', models.CharField(blank=True, max_length=3)),
                ('first_payment_only', models.BooleanField(default=False)),
                ('applies_to_all_plans', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('eligible_plans', models.ManyToManyField(blank=True, related_name='eligible_coupons', to='subscription.subscriptionplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='coupon.discount')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code_snapshot', models.CharField(editable=False, max_length=50)),
                ('discount_name_snapshot', models.CharField(editable=False, max_length=120)),
                ('discount_type_snapshot', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], editable=False, max_length=20)),
                ('discount_value_snapshot', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('discount_currency_snapshot', models.CharField(blank=True, editable=False, max_length=3)),
                ('discount_duration_snapshot', models.CharField(choices=[('once', 'Once'), ('repeating', 'Repeating'), ('forever', 'Forever')], editable=False, max_length=12)),
                ('duration_in_billing_cycles_snapshot', models.PositiveIntegerField(editable=False, null=True)),
                ('billing_cycles_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='coupon.coupon')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemption', to='subscription.payment')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='subscription.chatbotsubscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['coupon', 'user', '-redeemed_at'], name='promo_redeem_user_idx'), models.Index(fields=['subscription', 'is_active'], name='promo_redeem_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('original_amount__gte', 0), ('discount_amount__gte', 0), ('final_amount__gte', 0), ('discount_amount__lte', models.F('original_amount'))), name='promo_redeem_amounts_valid'), models.CheckConstraint(condition=models.Q(('final_amount', django.db.models.expressions.CombinedExpression(models.F('original_amount'), '-', models.F('discount_amount')))), name='promo_redeem_total_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='promo_discount_value_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), _negated=True), ('value__lte', 100), _connector='OR'), name='promo_discount_percent_lte'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration', 'repeating'), ('duration_in_billing_cycles__isnull', False)), models.Q(models.Q(('duration', 'repeating'), _negated=True), ('duration_in_billing_cycles__isnull', True)), _connector='OR'), name='promo_discount_cycles_valid'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='promo_coupon_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_purchase_amount__isnull', True), ('minimum_purchase_amount__gte', 0), _connector='OR'), name='promo_coupon_min_amount_gte_0'),
        ),
    ]
