# Generated by Django 5.1.7 on 2026-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_preserve_usage_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='usage_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('lead_insight_generation', 'Lead Insight Generation'), ('content_generation', 'Content generation')], db_index=True, max_length=30),
        ),
    ]
