# Generated by Django 5.1.7 on 2026-10-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_aiusage_usage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiusage',
            name='metadata',
        ),
    ]
