# Generated by Django 5.1.7 on 2026-08-29 08:17

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
import lead_capture.utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0012_widget_header_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('custom_fields', models.JSONField(blank=True, default=dict, validators=[lead_capture.utils.validators.validate_lead_custom_fields])),
                ('initial_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detected_country_code', models.CharField(blank=True, default='', max_length=5)),
                ('detected_city', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('disqualified', 'Disqualified')], db_index=True, default='new', max_length=30)),
                ('lead_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='chatbot.chatbot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCaptureConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('name_mode', models.CharField(choices=[('hidden', 'Hidden'), ('optional', 'Optional'), ('required', 'Required')], default='required', max_length=10)),
                ('email_mode', models.CharField(choices=[('hidden', 'Hidden'), ('optional', 'Optional'), ('required', 'Required')], default='required', max_length=10)),
                ('phone_mode', models.CharField(choices=[('hidden', 'Hidden'), ('optional', 'Optional'), ('required', 'Required')], default='optional', max_length=10)),
                ('address_mode', models.CharField(choices=[('hidden', 'Hidden'), ('optional', 'Optional'), ('required', 'Required')], default='hidden', max_length=10)),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Custom fields as label/value/mode objects. Values must be unique snake_case keys and modes must be optional or required.', validators=[lead_capture.utils.validators.validate_custom_field_config])),
                ('auto_collect', models.BooleanField(default=True, help_text='Allow the AI to proactively collect lead information.')),
                ('intro_message', models.TextField(blank=True, default='')),
                ('require_consent', models.BooleanField(default=False)),
                ('consent_message', models.TextField(blank=True, default='')),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_capture_config', to='chatbot.chatbot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead capture config',
                'verbose_name_plural': 'Lead Capture Config',
                'db_table': 'lead_capture_config',
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_notes', to='chatbot.chatbotuser')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lead_capture.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['chatbot', 'created_at'], name='lead_chatbot_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['chatbot', 'email'], name='lead_chatbot_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('custom_fields'), function='jsonb_typeof', output_field=models.CharField()), models.Value('object')), name='lead_custom_fields_object'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('lead_score__lte', 100)), name='lead_score_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='leadcaptureconfig',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('custom_fields'), function='jsonb_typeof', output_field=models.CharField()), models.Value('array')), name='lead_capture_custom_fields_array'),
        ),
        migrations.AddConstraint(
            model_name='leadcaptureconfig',
            constraint=models.CheckConstraint(condition=models.Q(('is_enabled', False), models.Q(('address_mode', 'hidden'), ('email_mode', 'hidden'), ('name_mode', 'hidden'), ('phone_mode', 'hidden'), _negated=True), django.db.models.lookups.GreaterThan(models.Func(models.F('custom_fields'), function='jsonb_array_length', output_field=models.IntegerField()), models.Value(0)), _connector='OR'), name='lead_capture_enabled_has_field'),
        ),
        migrations.AddConstraint(
            model_name='leadcaptureconfig',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Func(models.F('custom_fields'), function='jsonb_array_length', output_field=models.IntegerField()), '+', models.Case(models.When(name_mode='hidden', then=models.Value(0)), default=models.Value(1), output_field=models.IntegerField())), '+', models.Case(models.When(email_mode='hidden', then=models.Value(0)), default=models.Value(1), output_field=models.IntegerField())), '+', models.Case(models.When(phone_mode='hidden', then=models.Value(0)), default=models.Value(1), output_field=models.IntegerField())), '+', models.Case(models.When(address_mode='hidden', then=models.Value(0)), default=models.Value(1), output_field=models.IntegerField())), models.Value(10)), name='lead_capture_max_10_fields'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['lead', 'created_at'], name='lead_note_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadnote',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='lead_note_content_not_empty'),
        ),
    ]
