# Generated by Django 5.1.7 on 2026-08-31 07:50

import django.db.models.lookups
import lead_capture.utils.validators
from django.conf import settings
from django.db import migrations, models


DEFAULT_FIELD_DEFINITIONS = {
    "name": ("Name", "text"),
    "email": ("Email", "email"),
    "phone": ("Phone", "text"),
    "address": ("Address", "text"),
}


def consolidate_lead_fields(apps, schema_editor):
    Lead = apps.get_model("lead_capture", "Lead")
    LeadCaptureConfig = apps.get_model("lead_capture", "LeadCaptureConfig")

    for config in LeadCaptureConfig.objects.iterator():
        fields = []
        for value, (label, field_type) in DEFAULT_FIELD_DEFINITIONS.items():
            fields.append(
                {
                    "label": label,
                    "value": value,
                    "mode": getattr(config, f"{value}_mode"),
                    "type": field_type,
                }
            )
        for custom_field in config.custom_fields:
            fields.append({**custom_field, "type": "text"})
        config.collectable_fields = fields
        config.save(update_fields=["collectable_fields"])

    for lead in Lead.objects.iterator():
        collected_fields = dict(lead.custom_fields)
        for value in DEFAULT_FIELD_DEFINITIONS:
            field_value = getattr(lead, value)
            if field_value:
                collected_fields[value] = field_value
        lead.collected_fields = collected_fields
        lead.save(update_fields=["collected_fields"])


def split_lead_fields(apps, schema_editor):
    Lead = apps.get_model("lead_capture", "Lead")
    LeadCaptureConfig = apps.get_model("lead_capture", "LeadCaptureConfig")

    for config in LeadCaptureConfig.objects.iterator():
        custom_fields = []
        for field in config.collectable_fields:
            value = field.get("value")
            if value in DEFAULT_FIELD_DEFINITIONS:
                setattr(config, f"{value}_mode", field.get("mode", "hidden"))
            else:
                custom_fields.append(
                    {
                        key: field[key]
                        for key in ("label", "value", "mode")
                        if key in field
                    }
                )
        config.custom_fields = custom_fields
        config.save(
            update_fields=[
                "name_mode",
                "email_mode",
                "phone_mode",
                "address_mode",
                "custom_fields",
            ]
        )

    for lead in Lead.objects.iterator():
        collected_fields = dict(lead.collected_fields)
        for value in DEFAULT_FIELD_DEFINITIONS:
            setattr(lead, value, collected_fields.pop(value, ""))
        lead.custom_fields = collected_fields
        lead.save(
            update_fields=["name", "email", "phone", "address", "custom_fields"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_chatbotcapacity'),
        ('lead_capture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='lead_custom_fields_object',
        ),
        migrations.RemoveConstraint(
            model_name='leadcaptureconfig',
            name='lead_capture_custom_fields_array',
        ),
        migrations.RemoveConstraint(
            model_name='leadcaptureconfig',
            name='lead_capture_enabled_has_field',
        ),
        migrations.RemoveConstraint(
            model_name='leadcaptureconfig',
            name='lead_capture_max_10_fields',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_chatbot_email_idx',
        ),
        migrations.AddField(
            model_name='lead',
            name='collected_fields',
            field=models.JSONField(blank=True, default=dict, help_text="Values collected using the chatbot's lead configuration.", validators=[lead_capture.utils.validators.validate_collected_fields]),
        ),
        migrations.AddField(
            model_name='leadcaptureconfig',
            name='collectable_fields',
            field=models.JSONField(default=lead_capture.utils.validators.default_collectable_fields, help_text='Lead fields as label/value/mode/type objects. Name, email, phone, and address are provided by default.', validators=[lead_capture.utils.validators.validate_collectable_fields]),
        ),
        migrations.RunPython(consolidate_lead_fields, split_lead_fields),
        migrations.RemoveField(model_name='lead', name='address'),
        migrations.RemoveField(model_name='lead', name='custom_fields'),
        migrations.RemoveField(model_name='lead', name='email'),
        migrations.RemoveField(model_name='lead', name='name'),
        migrations.RemoveField(model_name='lead', name='phone'),
        migrations.RemoveField(model_name='leadcaptureconfig', name='address_mode'),
        migrations.RemoveField(model_name='leadcaptureconfig', name='custom_fields'),
        migrations.RemoveField(model_name='leadcaptureconfig', name='email_mode'),
        migrations.RemoveField(model_name='leadcaptureconfig', name='name_mode'),
        migrations.RemoveField(model_name='leadcaptureconfig', name='phone_mode'),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('collected_fields'), function='jsonb_typeof', output_field=models.CharField()), models.Value('object')), name='lead_collected_fields_object'),
        ),
        migrations.AddConstraint(
            model_name='leadcaptureconfig',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('collectable_fields'), function='jsonb_typeof', output_field=models.CharField()), models.Value('array')), name='lead_capture_fields_array'),
        ),
    ]
