# Generated by Django 5.1.7 on 2026-09-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_capture', '0002_consolidate_collectable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadcaptureconfig',
            name='intro_message',
        ),
    ]
