# Generated by Django 5.1.7 on 2026-10-06 15:10

import app.utils.validators
import django.db.models.deletion
import django.db.models.lookups
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_visitor_lead_one_to_one'),
        ('lead_capture', '0004_leadsignal_and_lead_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(help_text='Monday of the analyzed week.')),
                ('week_end', models.DateField(help_text='Sunday of the analyzed week.')),
                ('session_count', models.PositiveIntegerField(default=0, help_text='Distinct sessions the analyzed messages came from.')),
                ('visitor_message_count', models.PositiveIntegerField(default=0, help_text='Visitor messages in the window (before any AI cap).')),
                ('summary', models.TextField(blank=True, default='', help_text='Short narrative of what happened with visitors this week.')),
                ('topics', models.JSONField(blank=True, default=list, help_text='Products/services/subjects visitors asked about, as {topic, mentions, note} objects.')),
                ('frequently_asked_questions', models.JSONField(blank=True, default=list, help_text='Recurring visitor questions as {question, times_asked} objects.')),
                ('common_intents', models.JSONField(blank=True, default=list, help_text='Visitor intents (pricing, demo, support, ...) as {intent, mentions} objects.')),
                ('areas_of_improvement', models.JSONField(blank=True, default=list, help_text='Actionable suggestions derived from visitor questions.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Generation details: model, analyzed message count, caps, and token usage.', validators=[app.utils.validators.validate_json_object])),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        # 0004 dropped the lead_score column; PostgreSQL cascades the
        # lead_score_between_0_and_100 check constraint away with it, but the
        # migration state kept it. Reconcile the state and defensively drop
        # the constraint only if some database still carries it.
        migrations.RunSQL(
            sql=(
                'ALTER TABLE lead_capture_lead '
                'DROP CONSTRAINT IF EXISTS lead_score_between_0_and_100;'
            ),
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='lead',
                    name='lead_score_between_0_and_100',
                ),
            ],
        ),
        migrations.AddField(
            model_name='leadaiinsight',
            name='chatbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='chatbot.chatbot'),
        ),
        migrations.AddIndex(
            model_name='leadaiinsight',
            index=models.Index(fields=['chatbot', '-week_start'], name='lead_ai_insight_week_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadaiinsight',
            constraint=models.UniqueConstraint(fields=('chatbot', 'week_start'), name='unique_weekly_lead_ai_insight_per_chatbot'),
        ),
        migrations.AddConstraint(
            model_name='leadaiinsight',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('topics'), function='jsonb_typeof', output_field=models.CharField()), models.Value('array')), name='lead_ai_insight_topics_array'),
        ),
        migrations.AddConstraint(
            model_name='leadaiinsight',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('frequently_asked_questions'), function='jsonb_typeof', output_field=models.CharField()), models.Value('array')), name='lead_ai_insight_faqs_array'),
        ),
        migrations.AddConstraint(
            model_name='leadaiinsight',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('common_intents'), function='jsonb_typeof', output_field=models.CharField()), models.Value('array')), name='lead_ai_insight_intents_array'),
        ),
        migrations.AddConstraint(
            model_name='leadaiinsight',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('areas_of_improvement'), function='jsonb_typeof', output_field=models.CharField()), models.Value('array')), name='lead_ai_insight_improvements_array'),
        ),
    ]
