# Generated by Django 5.1.7 on 2026-10-08 10:23

import app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_capture', '0006_rename_leadsignal_summary_intent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadaiinsight',
            name='lead_ai_insight_improvements_array',
        ),
        migrations.RemoveField(
            model_name='leadaiinsight',
            name='areas_of_improvement',
        ),
        migrations.AlterField(
            model_name='leadaiinsight',
            name='common_intents',
            field=models.JSONField(blank=True, default=list, help_text='Visitor intents (pricing, demo, support, ...) as {intent} objects.'),
        ),
        migrations.AlterField(
            model_name='leadaiinsight',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Generation details: model, cost, and token usage.', validators=[app.utils.validators.validate_json_object]),
        ),
        migrations.AlterField(
            model_name='leadaiinsight',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='Products/services/subjects visitors asked about, as {topic, note} objects.'),
        ),
    ]
