# Generated by Django 5.1.7 on 2026-08-25 14:59

import django.contrib.postgres.fields
import django.db.models.deletion
import subscription.validators
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0008_chatbot_escalation_rule_chatbot_never_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.JSONField(default=dict, editable=False, validators=[subscription.validators.validate_subscription_snapshot])),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('bkash', 'bKash'), ('manual', 'Manual')], max_length=20)),
                ('renewal_mode', models.CharField(choices=[('provider_managed', 'Provider managed'), ('app_managed', 'Application managed'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('past_due', 'Past due'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], db_index=True, default='incomplete', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('provider_customer_id', models.CharField(blank=True, max_length=255)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='chatbot.chatbot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_chatbot_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('bkash', 'bKash'), ('manual', 'Manual')], max_length=20)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom')], max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_message_overage_unit_price', models.DecimalField(blank=True, decimal_places=6, help_text='Price for each AI message above the plan limit.', max_digits=12, null=True)),
                ('provider_overage_price_id', models.CharField(blank=True, help_text='Optional provider-side metered price identifier.', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('bkash', 'bKash'), ('manual', 'Manual')], max_length=20)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription'), ('overage', 'Usage overage'), ('one_time', 'One-time')], default='subscription', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requires_action', 'Requires action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=30)),
                ('billing_interval', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom')], max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('provider_customer_id', models.CharField(blank=True, max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, help_text='App-generated key preventing duplicate payment attempts.', max_length=255, null=True, unique=True)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscription.chatbotsubscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('plan_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscription.planprice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatbotsubscription',
            name='plan_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chatbot_subscriptions', to='subscription.planprice'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=140, unique=True)),
                ('plan_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom'), ('enterprise', 'Enterprise')], db_index=True, default='standard', max_length=20)),
                ('ai_message_limit', models.PositiveIntegerField(blank=True, help_text='Included messages for a monthly billing period. Annual subscription snapshots receive twelve times this allowance.', null=True)),
                ('file_size_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('knowledge_chunk_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_message_overage_enabled', models.BooleanField(default=False, help_text='Allow pay-per-use AI messages after the included limit is used.')),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('knowledge_base', 'Knowledge base'), ('human_handoff', 'Human handoff'), ('lead_capture', 'Lead capture'), ('appointment_booking', 'Appointment booking'), ('quotation_generation', 'Quotation generation'), ('order_taking', 'Order taking')], max_length=40), blank=True, default=list, size=None)),
                ('details_html', models.TextField(blank=True, help_text='Sanitize at render time, not at save time.')),
                ('is_free', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('requires_sales_contact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='planprice',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscription.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('bkash', 'bKash'), ('manual', 'Manual')], db_index=True, max_length=20)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('api_version', models.CharField(blank=True, max_length=40)),
                ('livemode', models.BooleanField(db_index=True, default=False)),
                ('payload', models.JSONField(default=dict)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='received', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='subscription.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processing_status', 'created_at'], name='sub_webhook_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='sub_webhook_provider_event_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status', '-created_at'], name='sub_payment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', '-created_at'], name='sub_payment_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_customer_id'], name='sub_payment_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__isnull', False), models.Q(('provider_reference', ''), _negated=True)), fields=('provider', 'provider_reference'), name='sub_payment_provider_ref_unique'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='sub_payment_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded__gte', 0), ('amount_refunded__lte', models.F('amount'))), name='sub_payment_refund_valid'),
        ),
        migrations.AddIndex(
            model_name='chatbotsubscription',
            index=models.Index(fields=['status', 'current_period_end'], name='sub_status_period_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotsubscription',
            index=models.Index(fields=['provider', 'provider_customer_id'], name='sub_provider_cust_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatbotsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['incomplete', 'active', 'past_due', 'paused', 'unpaid'])), fields=('chatbot',), name='sub_one_open_per_chatbot'),
        ),
        migrations.AddConstraint(
            model_name='chatbotsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_subscription_id__isnull', False), models.Q(('provider_subscription_id', ''), _negated=True)), fields=('provider', 'provider_subscription_id'), name='sub_provider_subscription_unique'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active', 'is_public', 'sort_order'], name='sub_plan_public_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['plan_type', 'is_active'], name='sub_plan_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(fields=('plan', 'provider', 'billing_interval', 'currency'), name='sub_planprice_unique_combo'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_price_id__isnull', False), models.Q(('provider_price_id', ''), _negated=True)), fields=('provider', 'provider_price_id'), name='sub_planprice_provider_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='sub_planprice_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.CheckConstraint(condition=models.Q(('ai_message_overage_unit_price__isnull', True), ('ai_message_overage_unit_price__gte', 0), _connector='OR'), name='sub_planprice_ppu_gte_0'),
        ),
    ]
