# Generated by Django 5.1.7 on 2026-10-03 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_remove_chatbotconfig_active_features_and_more'),
        ('subscription', '0005_add_lead_capture_to_supported_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('bkash', 'bKash'), ('manual', 'Manual')], max_length=20)),
                ('provider_customer_id', models.CharField(max_length=255)),
                ('provider_payment_method_id', models.CharField(max_length=255)),
                ('card_brand', models.CharField(blank=True, max_length=40)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payment_methods', to='chatbot.chatbot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['chatbot', 'provider', 'is_active'], name='sub_pm_chatbot_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_payment_method_id'), name='sub_pm_provider_id_unique'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('chatbot', 'provider'), name='sub_pm_one_default')],
            },
        ),
    ]
