# Generated by Django 5.1.7 on 2026-10-07 14:21

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_visitor_lead_one_to_one'),
        ('subscription', '0007_backfill_stripe_next_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('knowledge_base', 'Knowledge base'), ('human_handoff', 'Human handoff'), ('lead_capture', 'Lead capture'), ('lead_insights', 'Lead insights'), ('appointment_booking', 'Appointment booking'), ('ai_recommendations', 'AI recommendations')], max_length=40), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='EnterprisePlanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('knowledge_base', 'Knowledge base'), ('human_handoff', 'Human handoff'), ('lead_capture', 'Lead capture'), ('lead_insights', 'Lead insights'), ('appointment_booking', 'Appointment booking'), ('ai_recommendations', 'AI recommendations')], max_length=40), blank=True, default=list, size=None)),
                ('requested_ai_message_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_file_size_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_knowledge_chunk_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_daily_traffic', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approved_features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('knowledge_base', 'Knowledge base'), ('human_handoff', 'Human handoff'), ('lead_capture', 'Lead capture'), ('lead_insights', 'Lead insights'), ('appointment_booking', 'Appointment booking'), ('ai_recommendations', 'AI recommendations')], max_length=40), blank=True, default=list, size=None)),
                ('approved_ai_message_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_file_size_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_knowledge_chunk_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_plan_requests', to='chatbot.chatbot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enterprise_plan_requests', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscription.chatbotsubscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='sub_epr_status_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('chatbot',), name='sub_epr_one_pending_per_chatbot')],
            },
        ),
    ]
