# Generated by Django 5.1.7 on 2026-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_add_training_complete_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('update', 'Update'), ('maintenance', 'Maintenance'), ('notify', 'Notify'), ('new_message', 'New message'), ('session_started', 'Session started'), ('ai_notification', 'AI notification'), ('training_complete', 'Training complete')], db_index=True, default='general', help_text='The event represented by the notification.', max_length=24),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('global', 'Global'), ('chatbot', 'Chatbot'), ('user', 'User'), ('chat_session', 'Chat session'), ('workspace', 'Workspace')], db_index=True, help_text='The audience addressed by this notification.', max_length=20),
        ),
    ]
