# Generated by Django 5.1.7 on 2026-08-18 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(blank=True)),
                ('fallback_message', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('collect_user_info', models.BooleanField(default=False)),
                ('human_handoff_enabled', models.BooleanField(default=False)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='chatbot.chatbot')),
            ],
        ),
    ]
