# Generated by Django 5.1.7 on 2026-08-19 07:12

import chatbot.utils.validation
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbot_logo_chatbot_slug_chatbot_status_and_more'),
        ('workspace', '0002_workspace_details_and_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAllowedOrigin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(help_text='Allowed widget origin, for example https://www.example.com.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['origin'],
            },
        ),
        migrations.RemoveField(
            model_name='chatbotsettings',
            name='collect_user_info',
        ),
        migrations.RemoveField(
            model_name='chatbotuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chatbotuser',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='appointment_booking_enabled',
            field=models.BooleanField(default=False, help_text='Allow customers to book appointments or meetings.'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='knowledge_base_enabled',
            field=models.BooleanField(default=True, help_text="Allow answers grounded in the chatbot's knowledge bases."),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='lead_capture_enabled',
            field=models.BooleanField(default=False, help_text='Allow the chatbot to capture and qualify prospective leads.'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='order_taking_enabled',
            field=models.BooleanField(default=False, help_text='Allow the chatbot to collect and submit customer orders.'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='other_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Miscellaneous settings to operate chatbot', validators=[chatbot.utils.validation.validate_other_settings]),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='quotation_generation_enabled',
            field=models.BooleanField(default=False, help_text='Allow the chatbot to prepare pricing and quotations.'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='widget_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='widget_public_key',
            field=models.CharField(default=chatbot.utils.validation.generate_widget_public_key, editable=False, help_text='Public key embedded in the generated widget script.', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='widget_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Widget presentation settings such as colors, text, position, and launcher appearance.', validators=[chatbot.utils.validation.validate_widget_settings]),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled'), ('disabled_by_admin', 'Disabled by Admin')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='human_handoff_enabled',
            field=models.BooleanField(default=False, help_text='Allow the chatbot to handoff to the human assistant.'),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['workspace', 'status'], name='chatbot_workspace_status_idx'),
        ),
        migrations.AddField(
            model_name='chatbotallowedorigin',
            name='chatbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_origins', to='chatbot.chatbot'),
        ),
        migrations.AddField(
            model_name='chatbotallowedorigin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatbotallowedorigin',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatbotallowedorigin',
            index=models.Index(fields=['chatbot', 'is_active'], name='chatbot_origin_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatbotallowedorigin',
            constraint=models.UniqueConstraint(fields=('chatbot', 'origin'), name='unique_origin_per_chatbot'),
        ),
    ]
