# Generated by Django 5.1.7 on 2026-08-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chatbot_widget_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='welcome_message',
            field=models.TextField(blank=True, default='Hey, I am {chatbot_name}, I am here to answer anything you want to know about {business_name}.'),
        ),
    ]
