# Generated by Django 5.1.7 on 2026-08-29 09:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_widget_header_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_message_limit', models.PositiveIntegerField(blank=True, help_text='Maximum AI messages for the period; null means unlimited.', null=True)),
                ('current_ai_message_count', models.PositiveIntegerField(default=0)),
                ('file_size_limit_bytes', models.PositiveBigIntegerField(blank=True, help_text='Maximum stored knowledge bytes; null means unlimited.', null=True)),
                ('current_file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('knowledge_chunk_limit', models.PositiveIntegerField(blank=True, help_text='Maximum knowledge chunks; null means unlimited.', null=True)),
                ('current_knowledge_chunk_count', models.PositiveIntegerField(default=0)),
                ('active_features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('knowledge_base', 'Knowledge base'), ('human_handoff', 'Human handoff'), ('lead_capture', 'Lead capture'), ('appointment_booking', 'Appointment booking'), ('quotation_generation', 'Quotation generation'), ('order_taking', 'Order taking')], max_length=40), blank=True, default=list, size=None)),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='chatbot.chatbot')),
            ],
            options={
                'verbose_name': 'Chatbot capacity',
                'verbose_name_plural': 'Chatbot capacities',
            },
        ),
    ]
