# Generated by Django 5.1.7 on 2026-10-01 09:31

from django.db import migrations, models


def tag_existing_activity(apps, schema_editor):
    activity_logs = apps.get_model("chatbot", "ChatbotActivityLog")
    for module in ("chatbot", "knowledge", "leads", "appointment"):
        activity_logs.objects.using(schema_editor.connection.alias).filter(
            action__startswith=f"{module}.",
        ).update(module=module)


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_chatbotcapacity_test_ai_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotactivitylog',
            name='module',
            field=models.CharField(choices=[('chatbot', 'Chatbot'), ('knowledge', 'Knowledge'), ('leads', 'Leads'), ('appointment', 'Appointment'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.RunPython(tag_existing_activity, migrations.RunPython.noop),
    ]
