# Generated by Django 5.1.7 on 2026-10-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_rename_chatbotcapacity_chatbotconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotconfig',
            name='active_features',
        ),
        migrations.RemoveField(
            model_name='chatbotconfig',
            name='ai_message_limit',
        ),
        migrations.RemoveField(
            model_name='chatbotconfig',
            name='file_size_limit_bytes',
        ),
        migrations.RemoveField(
            model_name='chatbotconfig',
            name='knowledge_chunk_limit',
        ),
        migrations.RemoveField(
            model_name='chatbotconfig',
            name='test_ai_message_limit',
        ),
    ]
