# Generated by Django 5.1.7 on 2026-10-08 13:06

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_remove_unique_chatbot_name_per_workspace'),
        ('workspace', '0003_remove_workspaceinvitation_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatbot',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('chatbot_name'), models.F('workspace'), condition=models.Q(('is_deleted', False)), name='unique_active_chatbot_name_per_workspace'),
        ),
    ]
