# Generated by Django 5.1.7 on 2026-08-30 19:37

import appointment_booking.utils.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0013_chatbotcapacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBookingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('collectable_fields', models.JSONField(default=appointment_booking.utils.validators.default_collectable_fields, help_text='The predefined name, email, phone, date, and slot fields as label/value/mode/type objects.', validators=[appointment_booking.utils.validators.validate_collectable_fields])),
                ('appointment_duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('maximum_advance_days', models.PositiveSmallIntegerField(default=30)),
                ('max_appointments_per_day', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank for no daily limit.', null=True)),
                ('confirmation_message', models.TextField(blank=True, default='')),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_booking_config', to='chatbot.chatbot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment booking config',
                'verbose_name_plural': 'Appointment booking configs',
                'db_table': 'appointment_booking_config',
            },
        ),
        migrations.CreateModel(
            name='AppointmentBookingClosedDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, default='', help_text='Optional label, for example Eid holiday.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_dates', to='appointment_booking.appointmentbookingconfig')),
            ],
            options={
                'db_table': 'appointment_booking_closed_date',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentBookingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointment_booking.appointmentbookingconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_booking_schedule',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentBookingScheduleSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='appointment_booking.appointmentbookingschedule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_booking_schedule_slot',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_fields', models.JSONField(blank=True, default=dict, help_text="Values collected using the chatbot's booking configuration.", validators=[appointment_booking.utils.validators.validate_collected_fields])),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[appointment_booking.utils.validators.validate_appointment_metadata])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='chatbot.chatbot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['chatbot', 'starts_at'], name='appointment_bot_start_idx'), models.Index(fields=['chatbot', 'status', 'starts_at'], name='appointment_list_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='appointment_end_after_start'), models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('chatbot', 'starts_at'), name='appointment_unique_open_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointmentbookingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('appointment_duration_minutes__gt', 0)), name='appt_config_duration_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='appointmentbookingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_advance_days__gt', 0)), name='appt_config_advance_days_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='appointmentbookingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('max_appointments_per_day__isnull', True), ('max_appointments_per_day__gt', 0), _connector='OR'), name='appt_config_daily_limit_gt_0'),
        ),
        migrations.AddIndex(
            model_name='appointmentbookingcloseddate',
            index=models.Index(fields=['config', 'date', 'is_active'], name='appt_closed_date_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentbookingcloseddate',
            constraint=models.UniqueConstraint(fields=('config', 'date'), name='appt_closed_date_unique'),
        ),
        migrations.AddIndex(
            model_name='appointmentbookingschedule',
            index=models.Index(fields=['config', 'weekday', 'is_active'], name='appt_schedule_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentbookingschedule',
            constraint=models.UniqueConstraint(fields=('config', 'weekday'), name='appt_schedule_unique_weekday'),
        ),
        migrations.AddIndex(
            model_name='appointmentbookingscheduleslot',
            index=models.Index(fields=['schedule', 'is_active', 'start_time'], name='appt_slot_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentbookingscheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appt_slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointmentbookingscheduleslot',
            constraint=models.UniqueConstraint(fields=('schedule', 'start_time', 'end_time'), name='appt_slot_unique_window'),
        ),
    ]
