# Generated by Django 5.1.7 on 2026-08-25 10:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.extensions
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_knowledgetraininglog_unique_active_training_per_source'),
    ]

    operations = [
        pgvector.django.extensions.VectorExtension(),
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_documents', to='knowledge.knowledgebase')),
            ],
            options={
                'db_table': 'vector_documents',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['knowledge_base', 'chunk_index'], name='vector_kb_chunk_idx'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='vector_docu_metadat_ef9122_gin'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='vector_docs_search_vector_gin'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='vector_docs_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('knowledge_base', 'chunk_index'), name='unique_knowledge_vector_chunk')],
            },
        ),
    ]
