# Generated by Django 5.1.7 on 2026-10-08 12:47

import app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_unique_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='workspaceuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workspaceuser',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='workspaceuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workspaceuser',
            name='workspace',
        ),
        migrations.RemoveConstraint(
            model_name='workspace',
            name='unique_workspace_per_owner',
        ),
        migrations.AddField(
            model_name='workspace',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, validators=[app.utils.validators.validate_json_object]),
        ),
        migrations.DeleteModel(
            name='WorkspaceInvitation',
        ),
        migrations.DeleteModel(
            name='WorkspaceUser',
        ),
    ]
